; Generated by c68 v4.4.5, 25 Jan 95 (Jan 25 1995) from "./input.c"
	text
	even
_get_input:
	link	a6,#0
	;line	11
	move.w	#8,-(a7)
	jsr	__trap_1_w
L1:
	unlk	a6
	rts
_key_pressed:
	link	a6,#-4
	;line	17
	move.w	#11,-(a7)
	jsr	__trap_1_w
	addq.l	#2,a7
	ext.l	d0
	move.l	d0,-4(a6)
	;line	17
	tst.l	-4(a6)
	bne	L2
	;line	19
	moveq	#0,d0
	bra	L3
	bra	L4
L2:
	;line	22
	moveq	#1,d0
L4:
L3:
	unlk	a6
	rts
_get_time:
	link	a6,#-12
	;line	15
	pea	0
	move.w	#32,-(a7)
	jsr	__trap_1_wl
	addq.l	#6,a7
	move.l	d0,-12(a6)
	;line	16
	move.l	#1122,-4(a6)
	;line	17
	move.l	-4(a6),a0
	move.l	(a0),-8(a6)
	;line	18
	move.l	-12(a6),-(a7)
	move.w	#32,-(a7)
	jsr	__trap_1_wl
	;line	19
	move.l	-8(a6),d0
L5:
	unlk	a6
	rts
_get_base:
	link	a6,#-6
	movem.l	d3/d4,-(a7)
	;line	27
	move.l	8(a6),d4
	;line	29
	move.w	10(a6),d3
	;line	30
	move.w	d3,d0
	ext.l	d0
	divs	#256,d0
	swap	d0
	move.w	d0,d3
	;line	31
	move.w	#256,d0
	sub.w	d3,d0
	move.w	d0,d3
	;line	32
	ext.l	d3
	add.l	d3,d4
	;line	33
	move.l	d4,d0
L6:
	movem.l	(a7)+,d3/d4
	unlk	a6
	rts
_get_base32:
	link	a6,#-6
	movem.l	d3/d4,-(a7)
	;line	41
	move.l	8(a6),d4
	;line	43
	move.w	10(a6),d3
	;line	44
	move.w	d3,d0
	ext.l	d0
	divs	#256,d0
	swap	d0
	move.w	d0,d3
	;line	45
	move.w	#256,d0
	sub.w	d3,d0
	move.w	d0,d3
	;line	46
	ext.l	d3
	move.l	d3,d0
	asl.l	#2,d0
	add.l	d0,d4
	;line	47
	move.l	d4,d0
L7:
	movem.l	(a7)+,d3/d4
	unlk	a6
	rts
_main:
	link	a6,#-1096
	movem.l	d3/d4/d5/d6/d7/a3/a4,-(a7)
	lea	-1096(a6),a4
	lea	__trap_14_w,a3
	;line	88
	move.w	#2,-(a7)
	jsr	(a3)
	addq.l	#2,a7
	move.l	d0,d7
	move.w	#2,-(a7)
	jsr	(a3)
	addq.l	#2,a7
	move.l	d0,-8(a6)
	move.w	#2,-(a7)
	jsr	(a3)
	addq.l	#2,a7
	move.l	d0,d6
	pea	_buffer2
	jsr	_get_base
	addq.l	#4,a7
	move.l	d0,-16(a6)
	pea	_buffer2
	jsr	_get_base32
	addq.l	#4,a7
	move.l	d0,-20(a6)
	moveq	#0,d3
	moveq	#0,d5
	;line	88
	move.l	a4,-(a7)
	jsr	_start_game
	addq.l	#4,a7
	;line	89
	move.w	#10,-72(a6)
	;line	92
	move.l	a4,-(a7)
	move.l	d6,-(a7)
	move.l	d7,-(a7)
	jsr	_simple_render
	lea	12(a7),a7
	;line	93
	move.w	#1,-70(a6)
	;line	96
	bra	L9
L8:
	;line	98
	jsr	_get_time
	move.l	d0,d4
	;line	99
	move.l	d4,d0
	sub.l	-28(a6),d0
	move.l	d0,d5
	;line	101
	jsr	_key_pressed
	cmp.w	#1,d0
	bne	L11
	;line	103
	jsr	_get_input
	move.l	d0,d3
	;line	104
	move.l	d3,-(a7)
	pea	-96(a6)
	pea	-76(a6)
	jsr	_asynch_events
	lea	12(a7),a7
L11:
	;line	107
	tst.l	d5
	bls	L12
	;line	109
	move.l	a4,-(a7)
	pea	-96(a6)
	pea	-76(a6)
	jsr	_synch_events
	lea	12(a7),a7
	;line	110
	move.l	d4,-28(a6)
L12:
	;line	113
	move.l	a4,-(a7)
	move.l	d6,-(a7)
	move.l	d7,-(a7)
	jsr	_simple_render
	lea	12(a7),a7
	;line	114
	move.w	#37,-(a7)
	jsr	(a3)
	addq.l	#2,a7
L9:
	cmp.l	#1048689,d3
	bne	L8
L10:
	;line	119
	moveq	#0,d0
L13:
	movem.l	-1124(a6),d3/d4/d5/d6/d7/a3/a4
	unlk	a6
	rts
	globl	_get_input
	globl	_key_pressed
	bss
_buffer2:
	ds.b	38256
	globl	_buffer2
	globl	_get_time
	globl	_get_base
	globl	_get_base32
	globl	_main
