game: render.o raster.o model.o input.o breakout.o events.o buffer.o rast_asm.o in_asm.o
	cc68x -g raster.o render.o model.o breakout.o events.o buffer.o rast_asm.o in_asm.o -o game

tst: tst_in.o in_asm.o input.o buffer.o
	cc68x tst_in.o in_asm.o input.o buffer.o -o tst
	
events.o: events.c
	cc68x -g -c events.c

input.o: input.c
	cc68x -g -c input.c

breakout.o: breakout.c
	cc68x -g -c breakout.c

render.o: render.c render.h
	cc68x -g -c render.c

model.o: model.c model.h
	cc68x -g -c model.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c
	
buffer.o: buffer.c buffer.h
	cc68x -g -c buffer.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

in_asm.o: in_asm.s buffer.o
	gen -D -L2 in_asm.s
