; Generated by c68 v4.4.5, 25 Jan 95 (Jan 25 1995) from "./input.c"
	text
	even
_get_input:
	link	a6,#0
	;line	11
	move.w	#8,-(a7)
	jsr	__trap_1_w
L1:
	unlk	a6
	rts
_key_pressed:
	link	a6,#-4
	;line	17
	move.w	#11,-(a7)
	jsr	__trap_1_w
	addq.l	#2,a7
	ext.l	d0
	move.l	d0,-4(a6)
	;line	17
	tst.l	-4(a6)
	bne	L2
	;line	19
	moveq	#0,d0
	bra	L3
	bra	L4
L2:
	;line	22
	moveq	#1,d0
L4:
L3:
	unlk	a6
	rts
_get_time:
	link	a6,#-12
	;line	16
	pea	0
	move.w	#32,-(a7)
	jsr	__trap_1_wl
	addq.l	#6,a7
	move.l	d0,-12(a6)
	;line	17
	move.l	#1122,-4(a6)
	;line	18
	move.l	-4(a6),a0
	move.l	(a0),-8(a6)
	;line	19
	move.l	-12(a6),-(a7)
	move.w	#32,-(a7)
	jsr	__trap_1_wl
	;line	20
	move.l	-8(a6),d0
L5:
	unlk	a6
	rts
_get_base:
	link	a6,#-6
	movem.l	d3/d4,-(a7)
	;line	27
	move.l	8(a6),d4
	;line	28
	move.w	d4,d3
	;line	29
	clr.l	d0
	move.w	d3,d0
	divu	#256,d0
	swap	d0
	move.w	d0,d3
	;line	30
	move.w	#256,d0
	sub.w	d3,d0
	move.w	d0,d3
	;line	31
	move.l	d4,d0
	clr.l	d1
	move.w	d3,d1
	add.l	d1,d0
L6:
	movem.l	(a7)+,d3/d4
	unlk	a6
	rts
L8:
	dc.b	27,101,0
L7:
	dc.b	27,102,0
	even
_main:
	link	a6,#-2120
	movem.l	d3/d4/d5/d6/d7/a3/a4/a5,-(a7)
	lea	-2120(a6),a0
	move.l	a0,d5
	lea	__trap_14_w,a3
	;line	57
	move.w	#2,-(a7)
	jsr	(a3)
	addq.l	#2,a7
	move.l	d0,a4
	move.w	#2,-(a7)
	jsr	(a3)
	addq.l	#2,a7
	move.l	d0,-8(a6)
	pea	_buffer2
	jsr	_get_base
	addq.l	#4,a7
	move.l	d0,d7
	move.l	d7,-16(a6)
	move.l	d7,d6
	move.l	-16(a6),-24(a6)
	pea	_background
	jsr	_get_base
	addq.l	#4,a7
	move.l	d0,-28(a6)
	move.l	-28(a6),-32(a6)
	moveq	#-1,d3
	clr.l	-1040(a6)
	jsr	_get_time
	move.l	d0,-1052(a6)
	sub.l	a5,a5
	;line	57
	move.l	d5,-(a7)
	jsr	_start_game
	addq.l	#4,a7
	;line	59
	pea	1000
	move.l	d5,-(a7)
	pea	-1036(a6)
	jsr	_memcpy
	lea	12(a7),a7
	;line	61
	move.l	d5,-(a7)
	move.l	-32(a6),-(a7)
	jsr	_start_render
	addq.l	#8,a7
	;line	62
	move.l	d5,-(a7)
	move.l	-8(a6),-(a7)
	move.l	a4,-(a7)
	jsr	_simple_render
	lea	12(a7),a7
	;line	64
	pea	L7
	jsr	_printf
	addq.l	#4,a7
	;line	65
	pea	22+__iob
	jsr	_fflush
	addq.l	#4,a7
	;line	67
	bra	L10
L9:
	;line	69
	jsr	_key_pressed
	cmp.w	#1,d0
	bne	L12
	;line	71
	jsr	_get_input
	move.l	d0,-1040(a6)
	;line	72
	move.l	-1040(a6),-(a7)
	pea	-1120(a6)
	pea	-1100(a6)
	jsr	_asynch_events
	lea	12(a7),a7
L12:
	;line	75
	jsr	_get_time
	move.l	d0,-1048(a6)
	;line	76
	move.l	-1048(a6),d0
	sub.l	-1044(a6),d0
	move.l	d0,-1052(a6)
	;line	77
	tst.l	-1052(a6)
	bls	L13
	;line	79
	move.l	d5,-(a7)
	pea	-1120(a6)
	pea	-1100(a6)
	jsr	_synch_events
	lea	12(a7),a7
	;line	80
	pea	-1068(a6)
	pea	-1080(a6)
	move.l	d5,-(a7)
	pea	-1120(a6)
	pea	-1100(a6)
	jsr	_condition_events
	lea	20(a7),a7
	;line	81
	move.l	-1048(a6),-1044(a6)
	;line	83
	moveq	#0,d4
	bra	L15
L14:
	;line	85
	moveq	#0,d3
	bra	L19
L18:
	;line	87
	move.w	d3,d0
	muls	#10,d0
	move.l	d0,a0
	move.w	d4,d0
	muls	#200,d0
	add.l	d5,d0
	add.l	d0,a0
	lea	-1036(a6),a1
	move.w	d4,d0
	muls	#200,d0
	add.l	d0,a1
	move.w	d3,d0
	muls	#10,d0
	add.l	d0,a1
	move.w	4(a1),d0
	cmp.w	4(a0),d0
	beq	L22
	;line	89
	move.w	d3,-(a7)
	move.w	d4,-(a7)
	move.l	-32(a6),-(a7)
	jsr	_remove_brick
	addq.l	#8,a7
L22:
L21:
	addq.w	#1,d3
L19:
	cmp.w	#20,d3
	blt	L18
L20:
L17:
	addq.w	#1,d4
L15:
	cmp.w	#5,d4
	blt	L14
L16:
	;line	93
	pea	1000
	move.l	d5,-(a7)
	pea	-1036(a6)
	jsr	_memcpy
	lea	12(a7),a7
	;line	95
	pea	32000
	move.l	-28(a6),-(a7)
	move.l	d6,-(a7)
	jsr	_memcpy
	lea	12(a7),a7
	;line	96
	move.l	d5,-(a7)
	move.l	-24(a6),-(a7)
	move.l	d6,-(a7)
	jsr	_render
	lea	12(a7),a7
	;line	98
	cmp.w	#1,a5
	bne	L23
	;line	100
	move.l	d7,d6
	;line	101
	move.l	-16(a6),-24(a6)
	;line	102
	move.w	#-1,-(a7)
	move.l	a4,-(a7)
	pea	-1
	move.w	#5,-(a7)
	jsr	__trap_14_wllw
	lea	12(a7),a7
	;line	103
	sub.l	a5,a5
	bra	L24
L23:
	;line	107
	move.l	a4,d6
	;line	108
	move.l	-8(a6),-24(a6)
	;line	109
	move.w	#-1,-(a7)
	move.l	d7,-(a7)
	pea	-1
	move.w	#5,-(a7)
	jsr	__trap_14_wllw
	lea	12(a7),a7
	;line	110
	move.w	#1,a5
L24:
	;line	112
	move.w	#37,-(a7)
	jsr	(a3)
	addq.l	#2,a7
L13:
L10:
	cmp.l	#1048689,-1040(a6)
	bne	L9
L11:
	;line	116
	move.w	#-1,-(a7)
	move.l	a4,-(a7)
	pea	-1
	move.w	#5,-(a7)
	jsr	__trap_14_wllw
	lea	12(a7),a7
	;line	117
	move.w	#37,-(a7)
	jsr	(a3)
	addq.l	#2,a7
	;line	118
	pea	L8
	jsr	_printf
	addq.l	#4,a7
	;line	119
	pea	22+__iob
	jsr	_fflush
	;line	121
	moveq	#0,d0
L25:
	movem.l	-2152(a6),d3/d4/d5/d6/d7/a3/a4/a5
	unlk	a6
	rts
	globl	_get_input
	globl	_key_pressed
	bss
_buffer2:
	ds.b	32256
	globl	_buffer2
_background:
	ds.b	32256
	globl	_background
	globl	_get_time
	globl	_get_base
	globl	_main
