game: render.o raster.o model.o input.o breakout.o
	cc68x -g raster.o render.o model.o breakout.o -o game

input.o: input.c
	cc68x -g -c input.c
	
breakout.o: breakout.c
	cc68x -g -c breakout.c
	
render.o: render.c render.h
	cc68x -g -c render.c

model.o: model.c model.h
	cc68x -g -c model.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c
