game: render.o raster.o model.o input.o breakout.o events.o buffer.o rast_asm.o in_asm.o music.o psg.o effects.o splash.o
	cc68x -g raster.o render.o model.o breakout.o events.o buffer.o rast_asm.o in_asm.o music.o psg.o effects.o splash.o -o game

tst: tst_in.o in_asm.o input.o buffer.o
	cc68x tst_in.o in_asm.o input.o buffer.o -o tst
	
events.o: events.c
	cc68x -g -c events.c

input.o: input.c in_asm.o
	cc68x -g -c input.c

breakout.o: breakout.c
	cc68x -g -c breakout.c

render.o: render.c
	cc68x -g -c render.c

model.o: model.c
	cc68x -g -c model.c

raster.o: raster.c rast_asm.o
	cc68x -g -c raster.c
	
buffer.o: buffer.c
	cc68x -g -c buffer.c

tst_in.o: tst_in.c
	cc68x -c tst_in.c
	
rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

in_asm.o: in_asm.s buffer.o
	gen -D -L2 in_asm.s
	
music.o: music.c music.h
	cc68x -g -c music.c
	
psg.o: psg.c psg.h
	cc68x -g -c psg.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c
	
splash.o: splash.c render.o raster.o
	cc68x -g -c splash.c
