game: render.o raster.o model.o input.o breakout.o events.o rast_asm.o music.o psg.o effects.o
	cc68x -g raster.o render.o model.o breakout.o events.o rast_asm.o psg.o music.o effects.o -o game

events.o: events.c events.h
	cc68x -g -c events.c

input.o: input.c
	cc68x -g -c input.c

breakout.o: breakout.c
	cc68x -g -c breakout.c

render.o: render.c render.h
	cc68x -g -c render.c

model.o: model.c model.h
	cc68x -g -c model.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	
music.o: music.c music.h
	cc68x -g -c music.c
	
psg.o: psg.c psg.h
	cc68x -g -c psg.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c