tst: render.o raster.o model.o tester.o
	cc68x -g raster.o render.o model.o tester.o -o tst

tester.o: tester.c
	cc68x -g -c tester.c
	
render.o: render.c render.h
	cc68x -g -c render.c

model.o: model.c model.h
	cc68x -g -c model.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c
